### PR TITLE
fix: parsing error when `<script>` has attribute with empty value

### LINKED ISSUE #219: Parsing fails on script tag when id is empty
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I'm using [eslint-plugin-svelte](https://github.com/ota-meshi/eslint-plugin-svelte). (`*.svelte` file linting does not work with the parser alone. You should also use eslint-plugin-svelte with it.)
- [X] I'm sure the problem is a parser problem. (If you are not sure, search for the issue in [eslint-plugin-svelte](https://github.com/ota-meshi/eslint-plugin-svelte) repo and open the issue in [eslint-plugin-svelte](https://github.com/ota-meshi/eslint-plugin-svelte) repo if there is no solution.
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.23.1

### What version of `eslint-plugin-svelte` and ` svelte-eslint-parser` are you using?

- svelte-eslint-parser@0.18.2
- eslint-plugin-svelte@2.8.0

### What did you do?

<details>
<summary>Configuration</summary>

```
<!-- Paste your configuration here -->
```
</details>

```svelte
<head>
  <slot/>
  <link href="/style.css" rel="stylesheet">
  <script id="">const foo = 'Anything goes here';</script>
</head>
```

### What did you expect to happen?

No error

### What actually happened?

Parsing error: </script> attempted to close an element that was not open

### Link to Minimal Reproducible Example

Not required

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by ota-meshi**
close #219

### CODE REVIEW

File: src/parser/html.ts [hunk 1]
```diff
@@ -157,6 +157,17 @@ function parseAttributeValue(
       index,
     };
   }
+  if (valueFirstChar === quote) {
```
Comment (JounQin) [inline src/parser/html.ts:160]: Wil `id="'"`(single quote in double quotes) be a problem?

Comment (ota-meshi) [reply src/parser/html.ts:160]: Thank you for checking this PR!
I added that test case and checked it's ok.

https://github.com/ota-meshi/svelte-eslint-parser/pull/220/files#diff-55b441b2965ba2c4cfd83a1cb1cf9ac88d9de2dd24ff63a171637ac71bbd1256R42-R47
https://github.com/ota-meshi/svelte-eslint-parser/pull/220/files#diff-4206eb687f56ab83406ab73e9e563465dd77239185a78bad5de3ca6b8b6bdc49R189-R229

**Review by JounQin — APPROVED** [review]
