### PR TITLE
Fix error in member expr on LHS of reactive statement with TS

### LINKED ISSUE #213: Parsing error: ',' expected
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I'm using [eslint-plugin-svelte](https://github.com/ota-meshi/eslint-plugin-svelte). (`*.svelte` file linting does not work with the parser alone. You should also use eslint-plugin-svelte with it.)
- [X] I'm sure the problem is a parser problem. (If you are not sure, search for the issue in [eslint-plugin-svelte](https://github.com/ota-meshi/eslint-plugin-svelte) repo and open the issue in [eslint-plugin-svelte](https://github.com/ota-meshi/eslint-plugin-svelte) repo if there is no solution.
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.23.0

### What version of `eslint-plugin-svelte` and ` svelte-eslint-parser` are you using?

- svelte-eslint-parser@0.18.1
- eslint-plugin-svelte@2.7.0

### What did you do?

Updated from `svelte-eslint-parser@0.18.0` to `svelte-eslint-parser@0.18.1` 

### What did you expect to happen?

I expected eslint to lint my code like before

### What actually happened?

Eslint threw an error in one of components pointing to `614:1044` (component doesn't have that many lines), saying `error: Parsing error: ',' expected`

### Link to Minimal Reproducible Example

[Repro link](https://stackblitz.com/edit/vitejs-vite-c711vx?file=src/App.svelte)
 It must've been some change in `0.18.0 -> 0.18.1`, because downgrading to `0.18.0` works just fine
 

### Additional comments
It looks like it happens when a reactive assignment is bound to a property of an object.
Like: 
```ts
$: object.key = doSomething();
```
_No response_

### PR DESCRIPTION
**Pull request by ota-meshi**
close #213

### CODE REVIEW

File: src/parser/analyze-type/index.ts [hunk 1]
```diff
@@ -53,7 +53,12 @@ function appendDeclareSvelteVarsTypesFromAST(
           node.label.name !== "$" ||
           parent !== result.ast ||
           node.body.type !== "ExpressionStatement" ||
-          node.body.expression.type !== "AssignmentExpression"
+          node.body.expression.type !== "AssignmentExpression" ||
+          (node.body.expression.left.type !== "Identifier" &&
```
Comment (JounQin) [inline src/parser/analyze-type/index.ts:57]: I recommend to add some comments here, or at least link the original issue?

Comment (ota-meshi) [reply src/parser/analyze-type/index.ts:59]: Thank you for your review!
I added comments.

**Review by JounQin — APPROVED** [review]
